### ISSUE TITLE
gonfig derive macro fails when core crate is aliased (use ::core instead of core)

### ISSUE THREAD

**Issue by kvasanth-k** [itsparser/konfig#23]
### Description

The `#[derive(Gonfig)]` macro fails to compile when the `core` crate is aliased in the same file. This is a common pattern in Rust projects that have their own crate named `core`.

### Environment

- **gonfig version**: 0.1.10
- **Rust version**: 1.75.0+
- **OS**: macOS/Linux/Windows

### Minimal Reproduction

```rust
// This code fails to compile with gonfig 0.1.10

use core as tradesmith_core;  // Alias to avoid name conflict
use gonfig::Gonfig;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Gonfig)]
#[gonfig(env_prefix = "APP")]
pub struct Config {
    #[gonfig(nested)]
    pub server: ServerConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize, Gonfig)]
#[gonfig(env_prefix = "SERVER")]
pub struct ServerConfig {
    #[gonfig(default = "127.0.0.1")]
    pub host: String,
}
```

### Error Output

```
error[E0433]: failed to resolve: could not find `compile_error` in `core`
  --> src/config.rs:10:14
   |
10 |     #[gonfig(nested)]
   |              ^^^^^^ could not find `compile_error` in `core`
```

### Root Cause

The gonfig derive macro uses unqualified `core::` paths internally which resolve to the user's `core` alias instead of `std::core`.

### Proposed Fix

Update the gonfig derive macro to use **fully-qualified paths**:

```rust
// Change from:
quote! {
    core::compile_error!("...")
}

// To:
quote! {
    ::core::compile_error!("...")
}
```

Apply to all `core::` references: `compile_error`, `option::Option`, `result::Result`, etc.

### Impact

Blocks adoption in projects that have a crate named `core` (common in monorepos).

### Similar Issues

- serde: https://github.com/serde-rs/serde/issues/1465
- rust-lang: https://github.com/rust-lang/rust/issues/48214

### Temporary Workaround

Don't alias `core` in files using `#[derive(Gonfig)]`.

### Test Case

After fixing, add:

```rust
// tests/core_alias.rs
use core as my_core;
use gonfig::Gonfig;

#[derive(Gonfig)]
#[gonfig(env_prefix = "TEST")]
struct Config {
    field: String,
}
```

Happy to help test once fixed! Thanks for maintaining gonfig.
